name: GitHub Actions Demo
on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use Node.js version 14 (adjust as needed)
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build  # Run npm build script (adjust as needed)

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          SOURCE_DIR: "build"
      

      
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://cicd-bucket123
